from __future__ import annotations

import re
from pathlib import Path

_SLUG_STRIP = re.compile(r"[^a-z0-9]+")


def slugify(text: str, *, max_len: int = 60) -> str:
    s = _SLUG_STRIP.sub("-", text.lower()).strip("-")
    return s[:max_len].strip("-") or "plan"


def write_plan_doc(*, plan_dir: str | Path, idea: str, plan_md: str, date: str) -> str:
    """Write the plan markdown to <plan_dir>/<date>-<slug>.md and return the
    path. `date` is passed in (caller stamps it) for deterministic output."""
    out_dir = Path(plan_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{date}-{slugify(idea)}.md"
    header = f"# Plan: {idea}\n\n_Date: {date} · generated by kagura-planner_\n\n---\n\n"
    path.write_text(header + plan_md + "\n")
    return str(path)
